# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1f\n\x0eRequestMessage\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x0fResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\t29\n\tMyService\x12,\n\x07GetData\x12\x0f.RequestMessage\x1a\x10.ResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=17
  _globals['_REQUESTMESSAGE']._serialized_end=48
  _globals['_RESPONSEMESSAGE']._serialized_start=50
  _globals['_RESPONSEMESSAGE']._serialized_end=83
  _globals['_MYSERVICE']._serialized_start=85
  _globals['_MYSERVICE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
