name: DB Backfill Script CD
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploying Backfill script on AWS EC2
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Python setup
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: |
          pip install -r ./mf-karr-backend/requirements.txt
          python ./mf-karr-backend/scripts/dbDataBackfill.py
