name: DB Backfill Script CD
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploying Backfill Script image to AWS EC2
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          sudo docker login -u AWS -p $(aws ecr get-login-password) 715841355249.dkr.ecr.ap-south-1.amazonaws.com
          
      - name: Remove older container
        run: sudo docker rm -f db-backfill-script-container || true

      - name: Delete older image and Pull latest image
        run: |
          [ $(sudo docker images -q '715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/backfill-script' | wc -l) -ge 1 ] && sudo docker rmi $(sudo docker images -q '715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/backfill-script')
          sudo docker pull 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/backfill-script:latest

      - name: Run Docker Container
        run: sudo docker run -d --name db-backfill-script-container 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/backfill-script:latest -v .:/app
