name: DB Backfill Script CD
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploying Backfill Script image to AWS EC2
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          sudo docker login -u AWS -p $(aws ecr get-login-password) 715841355249.dkr.ecr.ap-south-1.amazonaws.com

      - name: Pull latest image
        run: sudo docker pull 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/backfill-script:latest

      - name: Remove older image
        run: sudo docker rm -f db-backfill-script-container || true

      - name: Run Docker Container
        run: sudo docker run --name db-backfill-script-container -v ~:/app 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/backfill-script:latest
