name: Backfill CD
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        pip install -r ./mf-karr-backend/requirements.txt
        python ./mf-karr-backend/scripts/dbUpdateCron.py
