# Make sure Docker is installed already on EC2 Instance and AWS CLI v2 is installed
# Also make sure ec2 ip is configured in environment.ts file
name: Frontend CD
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploying docker image to AWS EC2
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" >> $AWS_ACCESS_KEY_ID
        
      - name: Test
        run: echo $AWS_ACCESS_KEY_ID

      # - name: Docker Login
      #   run: sudo docker login -u AWS -p $(aws ecr get-login-password) 715841355249.dkr.ecr.ap-south-1.amazonaws.com

      # - name: Pull latest image
      #   run: sudo docker pull 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/mf-karr:latest

      # - name: Remove older image
      #   run: sudo docker rm -f mf-karr-container || true

      # - name: Run Docker Container
      #   run: sudo docker run -p 3000:3000 -e NEXT_PUBLIC_API_URL=http://13.232.234.139:8081 -d --name mf-karr-container 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/mf-karr:latest
